// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JVfpdJmKtrUtM8jPNUXrK4s4CtPOLzA',
    appId: '1:1032276204467:web:2e44247b225a2a4d9c49c6',
    messagingSenderId: '1032276204467',
    projectId: 'flutterloginindemo-f01e7',
    authDomain: 'flutterloginindemo-f01e7.firebaseapp.com',
    databaseURL: 'https://flutterloginindemo-f01e7-default-rtdb.firebaseio.com',
    storageBucket: 'flutterloginindemo-f01e7.appspot.com',
    measurementId: 'G-EN9EPN9J67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhNRlSlBW_ARFkEflXDoPdELLyRVUvmD4',
    appId: '1:1032276204467:android:3a74a7d216df00ea9c49c6',
    messagingSenderId: '1032276204467',
    projectId: 'flutterloginindemo-f01e7',
    databaseURL: 'https://flutterloginindemo-f01e7-default-rtdb.firebaseio.com',
    storageBucket: 'flutterloginindemo-f01e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnRF6C_WSNb83BijgSADjHl5EnqHcg_uU',
    appId: '1:1032276204467:ios:d0b230dfbf24a7a69c49c6',
    messagingSenderId: '1032276204467',
    projectId: 'flutterloginindemo-f01e7',
    databaseURL: 'https://flutterloginindemo-f01e7-default-rtdb.firebaseio.com',
    storageBucket: 'flutterloginindemo-f01e7.appspot.com',
    iosClientId: '1032276204467-51rshci0jo87admgrk3nbiam3h919f8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterloginindemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnRF6C_WSNb83BijgSADjHl5EnqHcg_uU',
    appId: '1:1032276204467:ios:eea6e864ae1eb7279c49c6',
    messagingSenderId: '1032276204467',
    projectId: 'flutterloginindemo-f01e7',
    databaseURL: 'https://flutterloginindemo-f01e7-default-rtdb.firebaseio.com',
    storageBucket: 'flutterloginindemo-f01e7.appspot.com',
    iosClientId: '1032276204467-k04pcu05gj0pvlumr16gt6cofqnu9d5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterloginindemo.RunnerTests',
  );
}
